### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by axieum** [axieum/fabric-example-mod#19]
To look in the `gradle.properties` file and upgrade all used dependencies to their latest version.

**Comment by SanthoshS20** [comment]
@axieum can i contribute to it?

**Comment by SanthoshS20** [comment]
https://github.com/axieum/fabric-example-mod/pull/21  Raised a PR

**Comment by SanthoshS20** [comment]
What is the labeler issue in the github actions?

**Comment by axieum** [comment]
Closed in #21.

@SanthoshS20 Thanks for the contribution. As for the labeler action failing, I'm unsure but may be related to actions/labeler#136?
