### ISSUE TITLE
`assets` label incorrectly applying to pull-requests

### ISSUE THREAD

**Issue by axieum** [axieum/fabric-example-mod#20]
### Expected behavior

For the `assets` label to not be applied to the affected pull-request.

### Observed/actual behavior

Please refer to affected pull-request: axieum/minecord#2

### Steps/models to reproduce

Create a pull-request that does not modify any file under the `**/assets/**` file glob.

### Version

n/a

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by nightlark** [comment]
I'll take a look at fixing this - I'm considering using the same labeler action elsewhere, so getting some experience with it would be good.
