### ISSUE TITLE
Update github workflow JDK version

### ISSUE THREAD

**Issue by theoparis** [axieum/fabric-example-mod#28]
It appears that the [**adopt** JDK distribution is now replaced by another one.](https://github.com/actions/setup-java#supported-distributions)

> NOTE: Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).

I could make a PR if needed.

**Comment by axieum** [comment]
Thanks for this! A PR is always welcome. 😊

**Comment by axieum** [comment]
Closed in #32
